<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script>
        alert("xinchao")
    </script>
    <script src="hello.js"></script>
    <script>
    // let a =5;
    // let b =7;
    // let c =a+b;
    // alert(c);
    </script>
    <script>
        let a = prompt('Nhap A');
        let b = prompt('Nhap B');
        let c = a * b;
        alert(c);
        console.log(c);
</script>

</head>

<body>
<h1> tôi ten la </h1>
<p> nguyen van a</p>
<p id="demo"></p>
<script>
document.getelementbyid("demo1").innerHTML = "Hello Dolly";
documment.getelementbyid("demo2").innerHTML = "How are you";
</script>
</body>


</html>