<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <title>Document</title>
</head>

<body>

    <!-- <script>
        let nam = parseInt(prompt("nhập số năm"));
        if (nam % 4 == 0) {
            if (nam % 100 == 0) {
                if (nam % 400 == 0) {
                    alert("nam nhuan");
                } else {
                    alert("ko phai nam nhuan");
                }
            } else {
                alert("nam nhuan");
            }
        } else {
            alert("ko phai nam nhuan");
        }
    </script> -->
    <script>
        {/* // let value = prompt('What is the official name of javascript');
        // if (value == 'ECMAScript') {
        //     alert('Right');
        // } else {
        //     alert("You don't know? ECMAScript");
        // } */}
    </script>
    <script>
        {/* // let username = prompt('Tên đăng nhập','')
        // if(username == 'lam') {
        //     let password = prompt('Mật khẩu đăng nhập', '')
        //     if(password == 'lam123'){
        //         alert('WELCOME');
        //     } else if(password == ''){
        //         alert('Canceled');
        //     } else {
        //         alert('Sai mật khẩu')
        //     }
        // } else if(username == ''){
        //     alert('Canceled');
        // } else {
        //     alert('Sai tài khoản');
        // } */}
    </script>
    <script>
        {/* var a = prompt("nhập a");
        var b = prompt("nhập b");
        a = parseInt(a);
        b = parseInt(b);
        if (a === 0) {
            if (b === 0) {
                document.write("vô số nghiệm");
            } else {
                document.write("vô nghiệm");
            }
        } else {
            var x = -b / a;
            document.write("nghiệm của phương trình là:" + x);
        } */}
    </script>
    <script>
        // var a = prompt("Nhập a");
        // var b = prompt("Nhập b");
        // a = parseInt(a);
        // b = parseInt(b);
        // if(a == 0){
        //     if(b == 0){
        //         document.write('vô số nghiệm')
        //     } else {
        //         document.write('vô nghiệm')
        //     }
        // } else {
        // var x = -b/a
        // document.write('nghiệm của phương trình=' + x ) 
        // }
    </script>
    <script>
        // var a = prompt("nhập a");
        // var b = prompt("nhập b");
        // var c = prompt("nhập c");
        // a = parseInt(a);
        // b = parseInt(b);
        // c = parseInt(c);
        // var d = b * b - 4 * a * c;
        // if (d < 0) {
        //     document.write("PT vô nghiệm");
        // } else if (d == 0) {
        //     var x = -b / 2 * a;
        //     document.write("PT có nghiệm x =" + x);
        // } else {
        //     var x1 = (-b + Math.sqrt(d)) / (2 * a);
        //     var x2 = (-b - Math.sqrt(d)) / (2 * a);
        //     document.write("phương trình có hai nghiệm phân biệt x1=" + x1 + "x2=" + x2);
        // } 
    </script>
</body>

</html>