<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        // If(condition) {
        //     đoạn mã
        // }
        // var thoitiet = "xau"
        // if (thoitiet == "dep") {
        //     alert("dichoi")
        // }
        // var thoitiet = "dep"
        // var cho_no = true;
        // if (thoitiet == "dep"&& cho_no == true) {
        //     alert("dichoi")
        // }

        /*
        // if(condition) {
        //     doan ma 1
        // } else{
        //     doan ma 2
        // }
        // */
        // var thoitiet = "dep"
        // if(thoitiet == "dep") {
        //     alert("dichoi")
        // } else{
        //     alert("onha")
        // }
        
    </script>
    <script>
        var a = 2
        var b = 2
        if (a == 0){
            if(b == 0){
                alert("vosonghiem")
            } else{
                alert("vonghiem")
            }
            
        }
        else{
            alert("conghiem x=-b/a")
        }
    </script>
    <script>
        /*
        if(condtion1){
            code1
        } else if(condtion){
            code2
        } else{
            code3
        }
        */
            
    </script>
    

</body>

</html>