<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
    // var vatly = parseInt(prompt('nhapdiem'));
    // var hoahoc = parseInt(prompt('nhapdiem')); 
    // var sinhhoc = parseInt(prompt('nhapdiem')); 
    // var tong = (vatly + hoahoc + sinhhoc);
    // var tongtb = tong/3
    // document.write('tong'+tong)
    // document.write('</br>')
    // document.write('tongtb'+tongtb)
    </script>
    <script>
        // var R = parseInt(prompt('nhap ban kinh hinh tron'))
        // const pi = 3.14;
        // var S = R*R*pi
        // document.write('dien tich S'+ S)
    </script>
    <script>
        var R = parseInt(prompt('nhap ban kinh hinh tron'))
        const pi = 3.14;
        var C = R*2*3.14
        document.write('chu vi C'+ C)
    </script>
</body>
</html>